version: "3.7"

services:
  mongo:
    image: mongo:3.6-xenial
    restart: always
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3.8.3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
