version: "3.7"

services:
  mongo:
    image: mongo:3.6-xenial
    restart: always
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3.8.3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  postgres:
    image: postgres:12.2
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
